In [1]:
import numpy as np

In [2]:
simple_list = [1,2,3]

In [3]:
np.array(simple_list)

array([1, 2, 3])

In [4]:
list_of_lists = [[1,2,3], [4,5,6], [7,8,9]]

In [5]:
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,21,5)

array([ 0,  5, 10, 15, 20])

In [8]:
ed = np.zeros(100)

In [9]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [11]:
a = np.eye(5)

In [12]:
np.random.rand(3,2)

array([[0.07177075, 0.51774442],
       [0.38860551, 0.02597771],
       [0.17366846, 0.33236351]])

In [13]:
a = np.random.randn(2,3)

In [14]:
np.random.randint(5,20,10)

array([10,  6, 17, 19,  8, 15, 14,  7, 11, 11])

In [15]:
sample_array = np.arange(30)

In [16]:
rand_array = np.random.randint(0,100,20)

In [17]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [18]:
rand_array.argmin()

19

In [19]:
sample_array.shape

(30,)

In [20]:
sample_array.reshape(1,30)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [21]:
sample_array.reshape(30,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29]])

In [22]:
sample_array.dtype

dtype('int32')

In [23]:
a.T

array([[ 0.90776923, -1.09345217],
       [-0.89688272, -2.09789477],
       [ 0.50259884, -0.45442867]])

In [24]:
a.T

array([[ 0.90776923, -1.09345217],
       [-0.89688272, -2.09789477],
       [ 0.50259884, -0.45442867]])

In [25]:
sample_array = np.arange(10,21)

In [26]:
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [27]:
sample_array[8]

18

In [28]:
sample_array[[2,5]]

array([12, 15])

In [29]:
sample_array[1:2] = 100

In [30]:
sample_array

array([ 10, 100,  12,  13,  14,  15,  16,  17,  18,  19,  20])

In [31]:
sample_array = np.arange(10,21)

In [32]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [33]:
sample_array = np.arange(10,21)
                        
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [34]:
subset_sample_array = sample_array[0:7]

subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [35]:
subset_sample_array[:]=1001

In [36]:
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

In [37]:
sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001,   17,   18,   19,   20])

In [38]:
copy_sample_array = sample_array.copy()

In [39]:
copy_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001,   17,   18,   19,   20])

In [40]:
copy_sample_array[:]=10
copy_sample_array

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [41]:
sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001,   17,   18,   19,   20])

In [42]:
sample_matrix = np.array(([50,20,1,23], [24,23,21,32], [76,54,32,12], [98,6,4,3]))

In [43]:
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 32],
       [76, 54, 32, 12],
       [98,  6,  4,  3]])

In [44]:
sample_matrix[0][3]

23

In [45]:
sample_matrix[0,3]

23

In [46]:
sample_matrix[3,:]

array([98,  6,  4,  3])

In [47]:
sample_matrix[3]

array([98,  6,  4,  3])

In [48]:
sample_matrix = np.array(([50,20,1,23,34], [24,23,21,32,34], [76,54,32,12,98], [98,6,4,3,67], [12,23,34,56,67]))

In [49]:
sample_matrix

array([[50, 20,  1, 23, 34],
       [24, 23, 21, 32, 34],
       [76, 54, 32, 12, 98],
       [98,  6,  4,  3, 67],
       [12, 23, 34, 56, 67]])

In [50]:
sample_matrix[:,(1,3)]

array([[20, 23],
       [23, 32],
       [54, 12],
       [ 6,  3],
       [23, 56]])

In [51]:
sample_matrix[:,(3,1)]

array([[23, 20],
       [32, 23],
       [12, 54],
       [ 3,  6],
       [56, 23]])

In [52]:
sample_array=np.arange(1,31)

In [53]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [54]:
bool = sample_array < 10

In [55]:
sample_array[bool]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
sample_array[sample_array <10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
a=11

In [58]:
sample_array[sample_array < a]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
sample_array + sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [60]:
sample_array / sample_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [61]:
10/sample_array

array([10.        ,  5.        ,  3.33333333,  2.5       ,  2.        ,
        1.66666667,  1.42857143,  1.25      ,  1.11111111,  1.        ,
        0.90909091,  0.83333333,  0.76923077,  0.71428571,  0.66666667,
        0.625     ,  0.58823529,  0.55555556,  0.52631579,  0.5       ,
        0.47619048,  0.45454545,  0.43478261,  0.41666667,  0.4       ,
        0.38461538,  0.37037037,  0.35714286,  0.34482759,  0.33333333])

In [62]:
sample_array + 1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [63]:
np.var(sample_array)

74.91666666666667

In [64]:
array = np.random.randn(6,6)

In [65]:
array

array([[-1.51976689, -0.75585807, -0.10333498,  2.36845837, -1.46926543,
        -0.55983817],
       [ 1.28196778, -0.64054485, -0.23400079,  0.23108569, -0.4873292 ,
         0.98640172],
       [ 0.84460573,  0.04446754, -0.75571602,  0.50075418,  0.71379458,
         1.14821434],
       [-0.30386245,  1.66494555, -1.74557194,  0.44463707, -0.47216929,
        -0.05072743],
       [-1.02574798, -1.31520641,  0.64270902, -0.2330157 ,  0.66949094,
        -0.64229394],
       [ 0.87354339, -2.02673381,  0.67358523, -0.38056304, -1.4977576 ,
        -0.32882291]])

In [66]:
np.std(array)

0.9950408226528128

In [67]:
np.mean(array)

-0.0960962719618072

In [68]:
sports = np.array(['golf', 'cric', 'fball', 'cric', 'Cric', 'fooseball'])

np.unique(sports)

array(['Cric', 'cric', 'fball', 'fooseball', 'golf'], dtype='<U9')

In [69]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [70]:
simple_array = np.arange(0,20)

In [71]:
simple_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [72]:
np.save('sample_array', sample_array)

In [73]:
np.savez('2_arrays.npz', a=sample_array, b=simple_array)

In [74]:
np.load('sample_array.npy')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [75]:
archive = np.load('2_arrays.npz')

In [76]:
archive['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [77]:
np.savetxt('text_file.txt', sample_array,delimiter=',')

In [78]:
np.loadtxt('text_file.txt', delimiter=',')

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30.])